import './globals.css';

import { Inter } from 'next/font/google';

import Footer from '~/components/layouts/Footer';
import MainNav from '~/components/layouts/MainNav';
import { ThemeProvider } from '~/components/ThemeProvider';
import { cn } from '~/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'bg-black')}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <MainNav />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
